application: picasatude
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- deferred: on

handlers:

- url: /googledb3ca354c8507eef.html
  static_files: googledb3ca354c8507eef.html
  upload: googledb3ca354c8507eef.html

- url: /
  static_files: index.html
  upload: index.html
  expiration: "30d"

- url: /images
  static_dir: images
  expiration: "365d"

- url: /css
  static_dir: css
  expiration: "365d"

- url: /.*
  script: main.py
