application: picasitude
version: test
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- deferred: on

handlers:

- url: /
  script: main.py

- url: /(.*\.html)
  static_files: html/\1
  upload: html/(.*\.html)
  expiration: "30d"

- url: /images
  static_dir: images
  expiration: "365d"

- url: /css
  static_dir: css
  expiration: "365d"

- url: /.*
  script: main.py
